version: '3.8'

services:
  my-java-app:
    image: telegram-bot-dream-stream:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m